name: Robot Afiliasi Tokopedia Baru

on:
  schedule:
    - cron: '0 * * * *' # Otomatis jalan setiap 1 jam
  workflow_dispatch: # Tombol manual

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode Repositori
        uses: actions/checkout@v4

      - name: Siapkan Sistem Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instal Bahan Pendukung
        run: |
          pip install requests beautifulsoup4

      - name: Nyalakan Robot Afiliasi
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main_bot.py
