name: Run Dedik AI Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: |
          pip install gspread oauth2client requests pandas

      - name: Execute Script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python main_bot.py


        
