name: Mesin Autopilot AI Dedik

on:
  schedule:
    # Otomatis jalan sendiri setiap 6 jam sekali (WIB) tanpa perlu kamu klik lagi
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  proses_dropship:
    runs-on: ubuntu-latest
    steps:
    - name: Siapkan pekerjaan
      uses: actions/checkout@v2
    - name: Siapkan Mesin Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Instal Robot Bahan Bakar (Perpustakaan)
      run: pip install requests beautifulsoup4
    - name: Bangunkan Dedik AI
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python main_bot.py
