name: Dedik AI Robot Otomatis

on:
  schedule:
    # Berjalan otomatis setiap jam 00:00 UTC (07:00 WIB)
    - cron: '0 0 * * *'
    # Berjalan otomatis setiap jam 12:00 UTC (19:00 WIB)
    - cron: '0 12 * * *'
  workflow_dispatch: # Tombol manual tetap ada untuk jaga-jaga

jobs:
  eksekusi:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Pustaka
        run: pip install requests gspread oauth2client

      - name: Jalankan Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          KREDENSIAL_GCP: ${{ secrets.GCP_CREDENTIALS }}
          ID_LEMBAR_KELIPATAN: ${{ secrets.SPREADSHEET_ID }}
        run: python main_bot.py
